---

- name: Install git
  homebrew:
    name: git
    state: latest

- name: Install git-lfs
  homebrew:
    name: git-lfs
    state: latest

- name: Install diff-so-fancy
  homebrew:
    name: diff-so-fancy
    state: latest

- name: Tap lazygit
  homebrew_tap:
    name: jesseduffield/lazygit

- name: Install lazygit
  homebrew:
    name: lazygit
    state: latest
